{{- if .Values.global.namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- include "cognee-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: namespace
{{- end }}
