{{- if and .Values.postgresql.enabled .Values.postgresql.primary.initdb.scripts }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "floe-platform.fullname" . }}-postgresql-init
  labels:
    {{- include "floe-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
data:
  {{- range $key, $val := .Values.postgresql.primary.initdb.scripts }}
  {{ $key }}: |
    {{ $val | nindent 4 }}
  {{- end }}
{{- end }}
