{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "floe-platform.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "floe-platform.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "floe-platform.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "floe-platform.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
