{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cube.fullname" . }}-sql
  labels:
    {{- include "cube.api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.sqlPort }}
      targetPort: sql
      protocol: TCP
      name: sql
  selector:
    {{- include "cube.api.selectorLabels" . | nindent 4 }}
{{- end }}
