{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cube.fullname" . }}-api
  labels:
    {{- include "cube.api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cube.api.selectorLabels" . | nindent 4 }}
{{- end }}
